CREATE TABLE BANK_ACCOUNT (
    ID INTEGER IDENTITY NOT NULL PRIMARY KEY,
    BANK_TYPE VARCHAR(20) NOT NULL,
    BANK_CODE VARCHAR(10) NOT NULL,
    BRANCH_CODE VARCHAR(10) NOT NULL,
    ACOCUNT_NUMBER VARCHAR(50)  NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
);